### ISSUE TITLE
Document bipartite SIMs

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/si#17]
As discussed with Lenka Hasova today, many thanks @lenkahas! I plan to make a 1st pass at this and ask for a review.

**Comment by lenkahas** [comment]
Validation measures can be translated from https://github.com/pysal/spint/blob/master/spint/utils.py

**Comment by Robinlovelace** [comment]
Aha that's great, I will take a look. Perhaps more importantly, which reproducible tests using that code, plus results, are a good place to start?

**Comment by lenkahas** [comment]
I would go with r2 and cpc :).

**Comment by Robinlovelace** [comment]
OK great, will give it a go!

**Comment by Robinlovelace** [comment]
Example from the README:

![image](https://user-images.githubusercontent.com/1825120/168485930-1adf9970-7dc1-4417-891e-2d5a1ec5e170.png)
